// Native package configuration audit: read-only checks, no secrets printed.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
const root=resolve(import.meta.dirname);
const target=process.argv[2];
if(!['android','ios'].includes(target))throw Error('Use android or ios');
const checks=[];
const add=(name,pass,details)=>checks.push({name,result:pass?'PASS':'REVIEW',details});
const config=JSON.parse(await readFile(resolve(root,'capacitor.config.json'),'utf8'));
add('Final app identifier',!config.appId.startsWith('com.example.'),config.appId+' (placeholder IDs are not release ready)');
add('No remote WebView URL',!config.server?.url,config.server?.url?'Remote server URL set':'Bundled app content');
if(target==='android'){
 const path=resolve(root,'android/app/src/main/AndroidManifest.xml');
 const xml=await readFile(path,'utf8');
 add('Cleartext traffic',!(/usesCleartextTraffic\\s*=\\s*["']true/.test(xml)),'Inspect merged release manifest too');
 add('Exported components',true,'Manual review required for merged manifest and exported components');
 add('Debug APK only',false,'Current GitHub APK is a debug build; do not submit to Play');
}else{
 const path=resolve(root,'ios/App/App/Info.plist');
 const get=(key)=>{try{return execFileSync('/usr/libexec/PlistBuddy',['-c','Print :'+key,path],{encoding:'utf8'}).trim()}catch{return null}};
 for(const key of ['NSPhotoLibraryUsageDescription','NSCameraUsageDescription','NSLocationWhenInUseUsageDescription'])
   add(key,Boolean(get(key)),get(key)?'Purpose text present':'Missing purpose text');
 add('Arbitrary network loads',!get('NSAppTransportSecurity:NSAllowsArbitraryLoads')||get('NSAppTransportSecurity:NSAllowsArbitraryLoads')==='false','Check final plist and external URLs');
 add('Simulator artifact only',false,'Unsigned simulator build is not an iPhone IPA');
}
add('Remote dependencies reviewed',false,'Manually audit Supabase, CDN, image hosts and OpenStreetMap');
const report=['# My Gym Tracker '+target+' native configuration audit','Generated by GitHub Actions; checks are preliminary, not a certification.','',...checks.map(c=>'- **'+c.result+'** '+c.name+': '+c.details),'','No production secrets or user data included.'].join('\\n');
await mkdir(resolve(root,'audit'),{recursive:true});
await writeFile(resolve(root,'audit',target+'-audit.md'),report+'\\n');
console.log(report);
